disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - trailing_whitespace
  - identifier_name
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - Fractal
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
